package com.o9pathshala.temp;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.o9pathshala.student.test.dto.QuestionDTO;
import com.o9pathshala.student.test.dto.SectionDTO;
import com.o9pathshala.student.test.dto.TestDTO;

public class Test {
	public static TestDTO getTest() {
		List<QuestionDTO> qList = new ArrayList<QuestionDTO>();
		QuestionDTO questiondto1 = null;
		List<String> options = null;
		List<Integer> correct = null;
		List<Integer> userAnswer = null;
		
		questiondto1 = new QuestionDTO();
		questiondto1.setAttempted(false);
		questiondto1.setQuestionId(1500000001);
		questiondto1.setContent("Pwhat is the capital of india?");
		options = new ArrayList<String>();
		options.add("Maharashtra\nAditya\nAgrawal");
		options.add("Delhi\nAditya\nAgrawal");
		options.add("Chennai\nAditya\nAgrawal");
		options.add("AP\nAditya\nAgrawal");
		options.add("Bombay\nAditya\nAgrawal");
		correct = new ArrayList<Integer>();
		correct.add(1);
		correct.add(2);
	
		userAnswer = new ArrayList<Integer>();
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setOptions(options);
		questiondto1.setCorrectOptions(correct);
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setMarks(0.00f);
		qList.add(questiondto1);

		questiondto1 = new QuestionDTO();
		questiondto1.setAttempted(false);
		questiondto1.setMarks(0.00f);
		questiondto1.setQuestionId(1500000002);
		questiondto1.setContent("Pwhat is the capital of France?");
		options = new ArrayList<String>();
		options.add("Maharashtra1");
		options.add("Delhi1");
		options.add("Chennai1");
		options.add("AP1");
		options.add("Bombay1");
		correct = new ArrayList<Integer>();
		correct.add(1);	
		userAnswer = new ArrayList<Integer>();
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setOptions(options);
		questiondto1.setCorrectOptions(correct);
		qList.add(questiondto1);

		questiondto1 = new QuestionDTO();
		questiondto1.setAttempted(false);
		questiondto1.setMarks(0.00f);
		questiondto1.setQuestionId(1500000002);
		questiondto1.setContent("Pwhat is the capital of France?");
		options = new ArrayList<String>();
		options.add("Maharashtra1");
		options.add("Delhi1");
		options.add("Chennai1");
		options.add("AP1");
		options.add("Bombay1");
		correct = new ArrayList<Integer>();
		correct.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setOptions(options);
		questiondto1.setCorrectOptions(correct);
		qList.add(questiondto1);

		questiondto1 = new QuestionDTO();
		questiondto1.setAttempted(false);
		questiondto1.setMarks(0.00f);
		questiondto1.setQuestionId(1500000003);
		questiondto1.setContent("Pwhat is the capital of England?");
		options = new ArrayList<String>();
		options.add("Maharashtra1");
		options.add("Delhi1");
		options.add("Chennai1");
		options.add("AP1");
		correct = new ArrayList<Integer>();
		correct.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setOptions(options);
		questiondto1.setCorrectOptions(correct);
		qList.add(questiondto1);

		questiondto1 = new QuestionDTO();
		questiondto1.setAttempted(false);
		questiondto1.setMarks(0.00f);
		questiondto1.setQuestionId(1500000004);
		questiondto1.setContent("Pwhat is the capital of UK?");
		options = new ArrayList<String>();
		options.add("Maharashtra1");
		options.add("Delhi1");
		options.add("Chennai1");
		options.add("AP1");
		options.add("Bombay1");
		correct = new ArrayList<Integer>();
		correct.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setOptions(options);
		questiondto1.setCorrectOptions(correct);
		qList.add(questiondto1);

		questiondto1 = new QuestionDTO();
		questiondto1.setAttempted(false);
		questiondto1.setMarks(0.00f);
		questiondto1.setQuestionId(1500000004);
		questiondto1.setContent("Pwhat is the capital of Italy?");
		options = new ArrayList<String>();
		options.add("Maharashtra45");
		options.add("Delhi74");
		options.add("Chennai184");
		options.add("AP124");
		options.add("Bombay11");
		correct = new ArrayList<Integer>();
		correct.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto1.setUserAnswers(userAnswer);
		questiondto1.setOptions(options);
		questiondto1.setCorrectOptions(correct);
		qList.add(questiondto1);

		List<SectionDTO> sList = new ArrayList<SectionDTO>();
		SectionDTO sectiondto = null;
		sectiondto = new SectionDTO();
		sectiondto.setSectionName("Physics");
		sectiondto.setSectionID(1400000001);
		Collections.shuffle(qList);
		sectiondto.setQuestions(qList);
		sList.add(sectiondto);

		List<QuestionDTO> w = new ArrayList<QuestionDTO>();

		QuestionDTO questiondto11 = null;
		List<String> options1 = null;
		List<Integer> correct1 = null;
		questiondto11 = new QuestionDTO();
		questiondto11.setAttempted(false);
		questiondto11.setMarks(0.00f);
		questiondto11.setQuestionId(1500000001);
		questiondto11.setContent("CMwhat is the capital of india?");
		options1 = new ArrayList<String>();
		options1.add("Maharashtra");
		options1.add("Delhi");
		options1.add("Chennai");
		options1.add("AP");
		options1.add("Bombay");
		correct1 = new ArrayList<Integer>();
		correct1.add(2);
		correct1.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto11.setUserAnswers(userAnswer);
		questiondto11.setOptions(options1);
		questiondto11.setCorrectOptions(correct1);
		w.add(questiondto11);

		questiondto11 = new QuestionDTO();
		questiondto11.setAttempted(false);
		questiondto11.setMarks(0.00f);
		questiondto11.setQuestionId(1500000002);
		questiondto11.setContent("CMwhat is the capital of France?");
		options1 = new ArrayList<String>();
		options1.add("Maharashtra1");
		options1.add("Delhi1");
		options1.add("Chennai1");
		options1.add("AP1");
		options1.add("Bombay1");
		correct1 = new ArrayList<Integer>();
		correct1.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto11.setUserAnswers(userAnswer);
		questiondto11.setOptions(options1);
		questiondto11.setCorrectOptions(correct1);
		w.add(questiondto11);

		questiondto11 = new QuestionDTO();
		questiondto11.setAttempted(false);
		questiondto11.setMarks(0.00f);
		questiondto11.setQuestionId(1500000002);
		questiondto11.setContent("CMwhat is the capital of France?");
		options1 = new ArrayList<String>();
		options1.add("Maharashtra1");
		options1.add("Delhi1");
		options1.add("Chennai1");
		options1.add("AP1");
		options1.add("Bombay1");
		correct1 = new ArrayList<Integer>();
		correct1.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto11.setUserAnswers(userAnswer);
		questiondto11.setOptions(options1);
		questiondto11.setCorrectOptions(correct1);
		w.add(questiondto11);

		questiondto11 = new QuestionDTO();
		questiondto11.setAttempted(false);
		questiondto11.setMarks(0.00f);
		questiondto11.setQuestionId(1500000003);
		questiondto11.setContent("CMwhat is the capital of England?");
		options1 = new ArrayList<String>();
		options1.add("Maharashtra1");
		options1.add("Delhi1");
		options1.add("Chennai1");
		options1.add("AP1");
		correct1 = new ArrayList<Integer>();
		correct1.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto11.setUserAnswers(userAnswer);
		questiondto11.setOptions(options1);
		questiondto11.setCorrectOptions(correct1);
		w.add(questiondto11);

		questiondto11 = new QuestionDTO();
		questiondto11.setAttempted(false);
		questiondto11.setMarks(0.00f);
		questiondto11.setQuestionId(1500000004);
		questiondto11.setContent("CMwhat is the capital of UK?");
		options1 = new ArrayList<String>();
		options1.add("Maharashtra1");
		options1.add("Delhi1");
		options1.add("Chennai1");
		options1.add("AP1");
		options1.add("Bombay1");
		correct1 = new ArrayList<Integer>();
		correct1.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto11.setUserAnswers(userAnswer);
		questiondto11.setOptions(options1);
		questiondto11.setCorrectOptions(correct1);
		w.add(questiondto11);

		questiondto11 = new QuestionDTO();
		questiondto11.setAttempted(false);
		questiondto11.setMarks(0.00f);
		questiondto11.setQuestionId(1500000004);
		questiondto11.setContent("CMwhat is the capital of Italy?");
		options1 = new ArrayList<String>();
		options1.add("Maharashtra45");
		options1.add("Delhi74");
		options1.add("Chennai184");
		options1.add("AP124");
		options1.add("Bombay11");
		correct1 = new ArrayList<Integer>();
		correct1.add(1);
		userAnswer = new ArrayList<Integer>();
		questiondto11.setUserAnswers(userAnswer);
		questiondto11.setOptions(options1);
		questiondto11.setCorrectOptions(correct1);
		w.add(questiondto11);

		sectiondto = new SectionDTO();
		Collections.shuffle(w);
		sectiondto.setQuestions(w);
		sectiondto.setSectionName("Chemistry");
		sectiondto.setSectionID(1400000002);
		sList.add(sectiondto);
		/*w.remove(1);
		Collections.shuffle(w);
		sectiondto.setQuestions(w);
		sList.add(sectiondto);

		sectiondto = new SectionDTO();
		sectiondto.setSectionName("Mathematics");
		sectiondto.setSectionID(1400000003);
		Collections.shuffle(w);
		w.remove(1);
		sectiondto.setQuestions(w);
		sList.add(sectiondto);*/

		TestDTO testdto = new TestDTO();
		testdto.setDuration(75);
		testdto.setId(1300000001);
		testdto.setSections(sList);
		testdto.setNegativeMark(1.00f);
		testdto.setPositiveMark(2.0f);
		testdto.setTestName("IIT JEE Test");
		return testdto;
	}
}
